apiVersion: v1
kind: ConfigMap
metadata:
  name: swapi-solution
data:
  .env: |
    POSTGRES_USER=myuser
    POSTGRES_PASSWORD=mypassword
    POSTGRES_HOST=my-db-host-amazom-aws.com
    POSTGRES_DB=mydb
    POSTGRES_PORT=5432
    REDIS_ADDRESS=my-redis-server.amazonaws.com:6379
