---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swapi-solution
  labels:
    app.kubernetes.io/name: swapi-solution
    app.kubernetes.io/instance: swapi-solution
    app_name: swapi-solution
    app.kubernetes.io/version: "0.0.1"
